[package]
name = "dtmrs-xa"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "XA two-phase commit helper for the resource-manager side (Postgres / MySQL)"

readme = "README.md"

[dependencies]
dtmrs-core = { path = "../dtmrs-core", version = "0.4.0" }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
